FROM node:16

WORKDIR /app

# 安装 pnpm
RUN npm config set registry https://registry.npmmirror.com/
RUN npm install -g pnpm@8.2.0

# 复制 package.json 和 pnpm-lock.yaml 到工作目录
COPY package.json pnpm-lock.yaml ./

# 安装应用程序的依赖
RUN pnpm install

# 复制应用程序的源代码到工作目录
COPY . .

# 应用程序使用的端口
EXPOSE 3000

# 启动应用程序
CMD ["node", "index.js"]