FROM nginx:latest

# 复制自定义的 nginx.conf 文件到容器的 /etc/nginx 目录中
COPY ./nginx.conf /etc/nginx/nginx.conf

# 将当前目录下的 index.html 文件复制到Nginx容器的默认网站目录
COPY ./index.html /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]